# Generated by Django 6.0.2 on 2026-02-28 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.PositiveSmallIntegerField()),
                ('minor', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['major', 'minor'],
                'unique_together': {('major', 'minor')},
            },
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_appearance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snippetz.pythonversion')),
            ],
        ),
    ]
