# Generated by Django 6.0.2 on 2026-03-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippetz', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pythonversion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pythonversion',
            constraint=models.UniqueConstraint(fields=('major', 'minor'), name='unique_python_version'),
        ),
    ]
